<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Contact</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Contact</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Match_Preference_Record_Page</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Match_Preference__c</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Match_Preference_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Match_Preference__c</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Profile_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Profile__c</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>Tab</actionName>
        <content>Home_Page_Default</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0070D2</headerColor>
        <logo>logo1</logo>
        <logoVersion>1</logoVersion>
        <shouldOverrideOrgTheme>true</shouldOverrideOrgTheme>
    </brand>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>Matchy</label>
    <navType>Standard</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Company Communities User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>ContractManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>ContractManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Work.com Only User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Work.com Only User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Cross Org Data Proxy User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Cross Org Data Proxy User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Custom: Marketing Profile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Custom: Marketing Profile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Custom: Support Profile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Custom: Support Profile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Custom: Sales Profile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Custom: Sales Profile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Community Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Community Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Community Plus Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Community Plus Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Community Plus User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Community User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Community User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>CustomerManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>CustomerManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Portal Manager Custom</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Portal Manager Custom</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Portal Manager Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Portal Manager Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Apps Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Apps Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Apps Plus Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Apps Plus Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Apps Plus User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Apps Plus User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Apps User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Apps User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Identity User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>External Identity User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Customer Community Plus User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Force.com - Free User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Force.com - Free User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Gold Partner User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Gold Partner User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Guest License User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Guest License User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>HighVolumePortal</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>HighVolumePortal</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>High Volume Customer Portal User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>High Volume Customer Portal User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Identity User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Identity User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>MarketingProfile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>MarketingProfile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Minimum Access - Salesforce</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Minimum Access - Salesforce</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Overage Customer Portal Manager Custom</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Overage Customer Portal Manager Custom</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Overage Customer Portal Manager Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Overage Customer Portal Manager Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Partner Community Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Partner Community Login User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Overage High Volume Customer Portal User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Overage High Volume Customer Portal User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Partner Community User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Partner Community User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Partner</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Partner</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Read Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Read Only</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>ServiceCloud</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>ServiceCloud</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Silver Partner User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Silver Partner User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>SolutionManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>SolutionManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>StandardAul</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>StandardAul</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Analytics Cloud Security User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>PlatformPortal</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>PlatformPortal</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Authenticated Website</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Authenticated Website</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Chatter External User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Chatter External User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Chatter Free User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Chatter Free User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Chatter Moderator User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Chatter Moderator User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Chatter Only User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Chatter Only User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Company Communities User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Analytics Cloud Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Analytics Cloud Integration User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <type>Flexipage</type>
        <profile>Analytics Cloud Security User</profile>
    </profileActionOverrides>
    <tabs>standard-home</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>Profile__c</tabs>
    <tabs>Match_Preference__c</tabs>
    <tabs>standard-Dashboard</tabs>
    <tabs>standard-report</tabs>
    <tabs>standard-Event</tabs>
    <tabs>Invoice__c</tabs>
    <tabs>Item_Master__c</tabs>
    <tabs>Invoice_Line_Item__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>Matchmaker_CRM_Project_UtilityBar</utilityBar>
</CustomApplication>
